plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-cayman

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
